spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/app_tech_db
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: F@b917109

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            format_sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
