server:
  servlet:
    context-path: /tech-shop

spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}
        driver-class-name: org.postgresql.Driver
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


email_admin: ${EMAIL_ADMIN}
password_admin: ${PASSWORD_ADMIN}