spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
        driver-class-name: org.postgresql.Driver
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            format_sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect